# Form implementation generated from reading ui file 'c:\Users\朱子豪\Desktop\ui\find.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class ui_find(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(546, 458)
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setGeometry(QtCore.QRect(220, 0, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(parent=Form)
        self.textEdit.setGeometry(QtCore.QRect(70, 40, 411, 31))
        self.textEdit.setOverwriteMode(False)
        self.textEdit.setTabStopDistance(77.0)
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(parent=Form)
        self.pushButton.setGeometry(QtCore.QRect(230, 90, 75, 24))
        self.pushButton.setObjectName("pushButton")
        self.textEdit_2 = QtWidgets.QTextEdit(parent=Form)
        self.textEdit_2.setGeometry(QtCore.QRect(70, 130, 411, 231))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 380, 91, 24))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=Form)
        self.pushButton_3.setGeometry(QtCore.QRect(330, 380, 91, 23))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "查找"))
        self.label.setText(_translate("Form", "查找书籍"))
        self.textEdit.setPlaceholderText(_translate("Form", "输入需要查找的书籍"))
        self.pushButton.setText(_translate("Form", "查找"))
        self.textEdit_2.setPlaceholderText(_translate("Form", "查找结果信息"))
        self.pushButton_2.setText(_translate("Form", "返回主界面"))
        self.pushButton_3.setText(_translate("Form", "清空"))
